# version: "3.9"
# services:
#   postgres:
#     container_name: classified_user_service
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: "UserServiceDb"
#       POSTGRES_USER: "postgres"
#       POSTGRES_PASSWORD: "12345"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

# volumes:
#   postgres-data:


services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zoo

  zoo:
    image: confluentinc/cp-zookeeper:7.8.0
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  redis:
    image: redis
    ports:
      - "6379:6379"