namespace Classified.Shared.Constants
{
    public static class RegionsCatalog
    {
        public static readonly Dictionary<CountryCode, List<RegionInfo>> Regions = new()
        {
            [CountryCode.US] = new()
            {
                new("AL", "Alabama", new[]{"AL","Alabama"}),
                new("AK", "Alaska", new[]{"AK","Alaska"}),
                new("AZ", "Arizona", new[]{"AZ","Arizona"}),
                new("AR", "Arkansas", new[]{"AR","Arkansas"}),
                new("CA", "California", new[]{"CA","California"}),
                new("CO", "Colorado", new[]{"CO","Colorado"}),
                new("CT", "Connecticut", new[]{"CT","Connecticut"}),
                new("DE", "Delaware", new[]{"DE","Delaware"}),
                new("FL", "Florida", new[]{"FL","Florida"}),
                new("GA", "Georgia", new[]{"GA","Georgia"}),
                new("HI", "Hawaii", new[]{"HI","Hawaii"}),
                new("ID", "Idaho", new[]{"ID","Idaho"}),
                new("IL", "Illinois", new[]{"IL","Illinois"}),
                new("IN", "Indiana", new[]{"IN","Indiana"}),
                new("IA", "Iowa", new[]{"IA","Iowa"}),
                new("KS", "Kansas", new[]{"KS","Kansas"}),
                new("KY", "Kentucky", new[]{"KY","Kentucky"}),
                new("LA", "Louisiana", new[]{"LA","Louisiana"}),
                new("ME", "Maine", new[]{"ME","Maine"}),
                new("MD", "Maryland", new[]{"MD","Maryland"}),
                new("MA", "Massachusetts", new[]{"MA","Massachusetts"}),
                new("MI", "Michigan", new[]{"MI","Michigan"}),
                new("MN", "Minnesota", new[]{"MN","Minnesota"}),
                new("MS", "Mississippi", new[]{"MS","Mississippi"}),
                new("MO", "Missouri", new[]{"MO","Missouri"}),
                new("MT", "Montana", new[]{"MT","Montana"}),
                new("NE", "Nebraska", new[]{"NE","Nebraska"}),
                new("NV", "Nevada", new[]{"NV","Nevada"}),
                new("NH", "New Hampshire", new[]{"NH","New Hampshire"}),
                new("NJ", "New Jersey", new[]{"NJ","New Jersey"}),
                new("NM", "New Mexico", new[]{"NM","New Mexico"}),
                new("NY", "New York", new[]{"NY","New York"}),
                new("NC", "North Carolina", new[]{"NC","North Carolina"}),
                new("ND", "North Dakota", new[]{"ND","North Dakota"}),
                new("OH", "Ohio", new[]{"OH","Ohio"}),
                new("OK", "Oklahoma", new[]{"OK","Oklahoma"}),
                new("OR", "Oregon", new[]{"OR","Oregon"}),
                new("PA", "Pennsylvania", new[]{"PA","Pennsylvania"}),
                new("RI", "Rhode Island", new[]{"RI","Rhode Island"}),
                new("SC", "South Carolina", new[]{"SC","South Carolina"}),
                new("SD", "South Dakota", new[]{"SD","South Dakota"}),
                new("TN", "Tennessee", new[]{"TN","Tennessee"}),
                new("TX", "Texas", new[]{"TX","Texas"}),
                new("UT", "Utah", new[]{"UT","Utah"}),
                new("VT", "Vermont", new[]{"VT","Vermont"}),
                new("VA", "Virginia", new[]{"VA","Virginia"}),
                new("WA", "Washington", new[]{"WA","Washington"}),
                new("WV", "West Virginia", new[]{"WV","West Virginia"}),
                new("WI", "Wisconsin", new[]{"WI","Wisconsin"}),
                new("WY", "Wyoming", new[]{"WY","Wyoming"}),
                new("DC", "District of Columbia", new[]{"DC","Washington DC","District of Columbia"})
            },

            [CountryCode.CA] = new()
            {
                new("AB", "Alberta", new[]{"AB","Alberta"}),
                new("BC", "British Columbia", new[]{"BC","British Columbia"}),
                new("MB", "Manitoba", new[]{"MB","Manitoba"}),
                new("NB", "New Brunswick", new[]{"NB","New Brunswick"}),
                new("NL", "Newfoundland and Labrador", new[]{"NL","Newfoundland","Labrador"}),
                new("NS", "Nova Scotia", new[]{"NS","Nova Scotia"}),
                new("ON", "Ontario", new[]{"ON","Ontario"}),
                new("PE", "Prince Edward Island", new[]{"PE","Prince Edward Island","PEI"}),
                new("QC", "Quebec", new[]{"QC","Québec","Quebec"}),
                new("SK", "Saskatchewan", new[]{"SK","Saskatchewan"}),
                new("NT", "Northwest Territories", new[]{"NT","Northwest Territories"}),
                new("NU", "Nunavut", new[]{"NU","Nunavut"}),
                new("YT", "Yukon", new[]{"YT","Yukon","Yukon Territory"})
            },
            [CountryCode.CH] = new()
            {
                new("AG", "Aargau", new[]{"AG","Aargau"}),
                new("AI", "Appenzell Innerrhoden", new[]{"AI","Appenzell Innerrhoden"}),
                new("AR", "Appenzell Ausserrhoden", new[]{"AR","Appenzell Ausserrhoden"}),
                new("BE", "Bern", new[]{"BE","Bern","Berne"}),
                new("BL", "Basel-Landschaft", new[]{"BL","Basel-Landschaft"}),
                new("BS", "Basel-Stadt", new[]{"BS","Basel-Stadt"}),
                new("FR", "Fribourg", new[]{"FR","Fribourg","Freiburg"}),
                new("GE", "Geneva", new[]{"GE","Genève","Geneva"}),
                new("GL", "Glarus", new[]{"GL","Glarus"}),
                new("GR", "Graubünden", new[]{"GR","Graubünden","Grisons"}),
                new("JU", "Jura", new[]{"JU","Jura"}),
                new("LU", "Lucerne", new[]{"LU","Lucerne","Luzern"}),
                new("NE", "Neuchâtel", new[]{"NE","Neuchâtel"}),
                new("NW", "Nidwalden", new[]{"NW","Nidwalden"}),
                new("OW", "Obwalden", new[]{"OW","Obwalden"}),
                new("SG", "St. Gallen", new[]{"SG","St. Gallen"}),
                new("SH", "Schaffhausen", new[]{"SH","Schaffhausen"}),
                new("SO", "Solothurn", new[]{"SO","Solothurn"}),
                new("SZ", "Schwyz", new[]{"SZ","Schwyz"}),
                new("TG", "Thurgau", new[]{"TG","Thurgau"}),
                new("TI", "Ticino", new[]{"TI","Ticino","Tessin"}),
                new("UR", "Uri", new[]{"UR","Uri"}),
                new("VD", "Vaud", new[]{"VD","Vaud"}),
                new("VS", "Valais", new[]{"VS","Valais","Wallis"}),
                new("ZG", "Zug", new[]{"ZG","Zug"}),
                new("ZH", "Zürich", new[]{"ZH","Zürich","Zurich"})
            }
        };
    } 
}