# services:
#   zoo:
#     image: confluentinc/cp-zookeeper:7.8.0
#     hostname: zoo
#     container_name: zoo
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_SERVERS: zoo1:2888:3888

#   kafka:
#     image: confluentinc/cp-kafka:7.8.0
#     hostname: kafka
#     container_name: kafka
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ZOOKEEPER_CONNECT: zoo:2181
#       KAFKA_BROKER_ID: 1
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
#     depends_on:
#       - zoo
 
#   redis:
#     image:  redis
#     ports:
#       - "6379:6379"

services:
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zoo

  zoo:
    image: confluentinc/cp-zookeeper:7.8.0
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  redis:
    image: redis
    ports:
      - "6379:6379"